import type { ITheme } from "@xterm/xterm";

export const TERMINAL_THEMES: Record<
  string,
  { label: string; theme: ITheme }
> = {
  matrix: {
    label: "Matrix Ops",
    theme: {
      background: "#020604",
      foreground: "#00ff9c",
      cursor: "#6bffce",
      cursorAccent: "#020604",
      selectionBackground: "#0a3d28",
      selectionForeground: "#d6ffe9",
      black: "#031008",
      red: "#ff4d6d",
      green: "#00ff9c",
      yellow: "#ffb454",
      blue: "#3ee6ff",
      magenta: "#a78bfa",
      cyan: "#3ee6ff",
      white: "#d7e5dc",
      brightBlack: "#17492f",
      brightRed: "#ff7a94",
      brightGreen: "#6bffce",
      brightYellow: "#ffd08a",
      brightBlue: "#8aefff",
      brightMagenta: "#c4b5fd",
      brightCyan: "#8aefff",
      brightWhite: "#f2fff9",
    },
  },
  cyberpunk: {
    label: "Cyberpunk",
    theme: {
      background: "#0b0b16",
      foreground: "#9beaff",
      cursor: "#ff006e",
      cursorAccent: "#0b0b16",
      selectionBackground: "#2a1245",
      selectionForeground: "#ffe6f2",
      red: "#ff006e",
      green: "#00ffc8",
      yellow: "#ffd166",
      blue: "#48bfe3",
      magenta: "#c77dff",
      cyan: "#80ffdb",
      white: "#d9f6ff",
      brightBlack: "#3a3a5e",
    },
  },
  void: {
    label: "Void Light",
    theme: {
      background: "#07090d",
      foreground: "#d3dbe4",
      cursor: "#3ee6ff",
      cursorAccent: "#07090d",
      selectionBackground: "#1c2a3a",
      red: "#ff6b81",
      green: "#7ef0a8",
      yellow: "#ffd479",
      blue: "#6cb6ff",
      magenta: "#b79bff",
      cyan: "#5ee4ff",
      white: "#e6edf5",
      brightBlack: "#3f4c5c",
    },
  },
  amber: {
    label: "Amber CRT",
    theme: {
      background: "#0a0601",
      foreground: "#ffb000",
      cursor: "#ffd479",
      cursorAccent: "#0a0601",
      selectionBackground: "#3d2802",
      red: "#ff5c38",
      green: "#c8ff00",
      yellow: "#ffd000",
      blue: "#ff9e3d",
      magenta: "#ff7a00",
      cyan: "#ffe08a",
      white: "#fff3d6",
      brightBlack: "#5c4200",
    },
  },
  ghost: {
    label: "Ghost",
    theme: {
      background: "#000000",
      foreground: "#c9c9c9",
      cursor: "#ffffff",
      cursorAccent: "#000000",
      selectionBackground: "#2b2b2b",
      red: "#ff5f5f",
      green: "#5fff8f",
      yellow: "#ffff5f",
      blue: "#5fafff",
      magenta: "#d787ff",
      cyan: "#5fffff",
      white: "#ffffff",
      brightBlack: "#4d4d4d",
    },
  },
};

export type ThemeName = keyof typeof TERMINAL_THEMES;
